-- PRC-05C: Commercial Price Workflow RPCs + Forward Integrity Hardening
-- Baseline: b2235b659e48b654b64df42e31c6bc68d32a2689 (COMMERCIAL_PRICE_SCHEMA_VERIFIED)
-- Migrations 001-033 are IMMUTABLE.
--
-- This migration delivers the authoritative commercial-price workflow layer over
-- the trusted PRC-05B schema:
--   A. Forward-only integrity hardening discovered during the PRC-05C
--      pre-implementation audit:
--      A1. Inactive commercial_price_tables MUST NOT receive new versions,
--          via RPC OR direct DML (PRC-05A invariant).
--      A2. origin_type = 'pricing_engine' provenance MUST be generated by a
--          trusted server-side RPC. Direct DML fabrication is blocked.
--      A3. New commercial_price_exceptions requests MUST be blocked when
--          the parent version has left the editable lifecycle
--          (scheduled/active/superseded/cancelled).
--   B. Table identity RPCs (create / update / status)
--   C. Concurrency-safe version allocation RPC
--   D. Manual commercial item RPCs (add / update price / delete)
--   E. Trusted engine-derived item RPC (only path to pricing_engine origin)
--   F. Atomic clone version RPC with catalog snapshot refresh + lineage
--   G. Server-side bulk draft price adjustments (percentage / fixed / rounding)
--   H. Commercial exception request / decision RPCs
--   I. Workflow RPCs (submit / return-to-draft / approve / cancel)
--   J. Publish readiness validator (read-only JSONB result)
--   K. Publish RPC (immediate / future / predecessor continuity)
--   L. Idempotent scheduled→active cutover RPC
--   M. Permission / grant / revoke
--
-- Patterns follow PRC-03B/04C conventions:
--   - SECURITY DEFINER + SET search_path = public
--   - Server-derived auth.uid()
--   - app.commercial_price_rpc_active session gate for trigger validation
--   - FOR UPDATE locking for concurrency-safe version allocation
--   - REVOKE FROM PUBLIC/anon; GRANT to authenticated for application-facing

-- ============================================================
-- A1. Inactive parent → no new version (forward integrity)
-- ============================================================
-- PRC-05A section 6 invariant: an inactive commercial_price_tables row cannot
-- receive a new commercial_price_table_versions row via RPC OR direct DML.
-- The existing 032 trigger fn_cptv_table_same_org only enforces org membership;
-- status is NOT enforced. This trigger closes the gap FORWARD-ONLY.

CREATE OR REPLACE FUNCTION public.fn_cptv_parent_active()
RETURNS trigger AS $$
DECLARE
  v_status text;
BEGIN
  SELECT status INTO v_status
  FROM commercial_price_tables
  WHERE id = NEW.commercial_price_table_id;

  IF v_status IS NULL THEN
    RAISE EXCEPTION 'commercial_price_table_id not found';
  END IF;

  IF v_status <> 'active' THEN
    RAISE EXCEPTION 'Cannot create a version of an inactive commercial price table (status=%)', v_status;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS trg_cptv_parent_active ON commercial_price_table_versions;
CREATE TRIGGER trg_cptv_parent_active
  BEFORE INSERT ON commercial_price_table_versions
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_cptv_parent_active();

-- ============================================================
-- A2. Engine provenance spoof guard (forward integrity)
-- ============================================================
-- PRC-05A invariant: origin_type = 'pricing_engine' provenance MUST come from
-- a trusted server-side RPC that calls fn_simulate_price. Direct browser DML
-- is blocked. The existing 032 fn_cpi_provenance_same_org trigger only checks
-- cross-org FK consistency — it does NOT prevent fabrication.
--
-- Allowed paths:
--   - controlled RPC sets app.commercial_price_rpc_active = 'true'
--     (fn_add_commercial_price_item_from_engine and fn_clone_*)
--   - manual items with origin_type = 'manual' (no gate needed)
-- The gate is required so that the same trigger that blocks fabrication also
-- permits cloning and engine-derived item creation.

CREATE OR REPLACE FUNCTION public.fn_cpi_engine_provenance_guard()
RETURNS trigger AS $$
DECLARE
  v_is_rpc boolean;
BEGIN
  v_is_rpc := COALESCE((current_setting('app.commercial_price_rpc_active', true) = 'true'), false);

  -- No engine provenance involved → allow
  IF NEW.origin_type IS DISTINCT FROM 'pricing_engine' THEN
    RETURN NEW;
  END IF;

  IF NOT v_is_rpc THEN
    RAISE EXCEPTION 'origin_type=pricing_engine provenance must be created via the engine-derived item RPC';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS trg_cpi_engine_provenance_guard ON commercial_price_items;
CREATE TRIGGER trg_cpi_engine_provenance_guard
  BEFORE INSERT OR UPDATE ON commercial_price_items
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_cpi_engine_provenance_guard();

-- ============================================================
-- A3. Exception parent-state hardening (forward integrity)
-- ============================================================
-- New exception requests MUST be blocked once the parent version has left the
-- editable lifecycle (scheduled / active / superseded / cancelled). Existing
-- 032 fn_cpe_integrity and fn_cpe_status_transition enforce item/version
-- consistency but do NOT enforce parent lifecycle state.
--
-- This invariant is enforced unconditionally (no gate) — no path can create a
-- new exception against a published-lifecycle version.

CREATE OR REPLACE FUNCTION public.fn_cpe_parent_editable()
RETURNS trigger AS $$
DECLARE
  v_status text;
BEGIN
  SELECT status INTO v_status
  FROM commercial_price_table_versions
  WHERE id = NEW.commercial_price_table_version_id;

  IF v_status IS NULL THEN
    RAISE EXCEPTION 'commercial_price_table_version_id not found';
  END IF;

  IF v_status NOT IN ('draft','under_review','approved') THEN
    RAISE EXCEPTION 'Cannot create commercial price exception for version with status % (allowed: draft, under_review, approved)', v_status;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS trg_cpe_parent_editable ON commercial_price_exceptions;
CREATE TRIGGER trg_cpe_parent_editable
  BEFORE INSERT ON commercial_price_exceptions
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_cpe_parent_editable();

-- ============================================================
-- B1. fn_create_commercial_price_table — stable identity create
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_create_commercial_price_table(
  p_organization_id uuid,
  p_code            text,
  p_name            text,
  p_description     text DEFAULT NULL
)
RETURNS uuid AS $$
DECLARE
  v_user_id  uuid;
  v_table_id uuid;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF NOT is_member_of(p_organization_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.create', p_organization_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.create)';
  END IF;

  INSERT INTO commercial_price_tables (
    organization_id, code, name, description,
    status, created_by, updated_by
  ) VALUES (
    p_organization_id, p_code, p_name, p_description,
    'active', v_user_id, v_user_id
  ) RETURNING id INTO v_table_id;

  RETURN v_table_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_create_commercial_price_table(uuid, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_create_commercial_price_table(uuid, text, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_create_commercial_price_table(uuid, text, text, text) TO authenticated;

-- ============================================================
-- B2. fn_update_commercial_price_table — stable mutable fields
-- ============================================================
-- Code immutability is enforced by the existing 032 fn_cpt_normalize_code
-- trigger (history-protection). This RPC only mutates name / description.

CREATE OR REPLACE FUNCTION public.fn_update_commercial_price_table(
  p_table_id    uuid,
  p_name        text DEFAULT NULL,
  p_description text DEFAULT NULL
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
  v_has_history boolean;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT organization_id, status INTO v_org_id, v_status
  FROM commercial_price_tables
  WHERE id = p_table_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Commercial price table not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.edit', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.edit)';
  END IF;

  -- Inactive tables retain historical versions but cannot be edited for new
  -- workflow. Allow editing identity only when the table is active (so an
  -- existing commercial operator can still fix typos before creating more
  -- versions). Reactivation re-enables full edit lifecycle.
  IF v_status <> 'active' THEN
    RAISE EXCEPTION 'Cannot edit inactive commercial price table';
  END IF;

  -- At least one field must be provided
  IF p_name IS NULL AND p_description IS NULL THEN
    RAISE EXCEPTION 'At least one of name or description must be provided';
  END IF;

  -- Reject empty/whitespace name if explicitly provided
  IF p_name IS NOT NULL AND btrim(p_name) = '' THEN
    RAISE EXCEPTION 'name cannot be empty or whitespace only';
  END IF;

  UPDATE commercial_price_tables
  SET name        = COALESCE(p_name, name),
      description = CASE WHEN p_description IS NULL THEN description ELSE p_description END,
      updated_by  = v_user_id
  WHERE id = p_table_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_update_commercial_price_table(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_update_commercial_price_table(uuid, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_update_commercial_price_table(uuid, text, text) TO authenticated;

-- ============================================================
-- B3. fn_set_commercial_price_table_status — active ↔ inactive
-- ============================================================
-- Inactivation must NOT mutate or supersede existing published versions;
-- historical reproducibility must be preserved (table-specific resolver still
-- works for any historical reference date). Reactivation is supported.

CREATE OR REPLACE FUNCTION public.fn_set_commercial_price_table_status(
  p_table_id uuid,
  p_status   text
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_current text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_status IS NULL OR p_status NOT IN ('active','inactive') THEN
    RAISE EXCEPTION 'Invalid status % (allowed: active, inactive)', p_status;
  END IF;

  SELECT organization_id, status INTO v_org_id, v_current
  FROM commercial_price_tables
  WHERE id = p_table_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Commercial price table not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.edit', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.edit)';
  END IF;

  IF v_current = p_status THEN
    RETURN;
  END IF;

  -- Inactivation: do not mutate/supersede existing published versions.
  -- (Reactivation is a no-op for the published versions themselves.)
  UPDATE commercial_price_tables
  SET status     = p_status,
      updated_by = v_user_id
  WHERE id = p_table_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_set_commercial_price_table_status(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_set_commercial_price_table_status(uuid, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_set_commercial_price_table_status(uuid, text) TO authenticated;

-- ============================================================
-- C. fn_create_commercial_price_table_version — concurrency-safe allocation
-- ============================================================
-- Locks the parent commercial_price_tables row FOR UPDATE so that two
-- concurrent calls produce distinct consecutive version_numbers (DEC-044
-- applied to commercial versions).

CREATE OR REPLACE FUNCTION public.fn_create_commercial_price_table_version(
  p_commercial_price_table_id uuid,
  p_valid_from                date,
  p_valid_to                  date DEFAULT NULL,
  p_version_label             text DEFAULT NULL,
  p_notes                     text DEFAULT NULL
)
RETURNS TABLE (version_id uuid, version_number integer) AS $$
DECLARE
  v_user_id      uuid;
  v_org_id       uuid;
  v_version_num  integer;
  v_version_id   uuid;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  -- Lock the parent stable table to serialize version_number allocation.
  SELECT cpt.organization_id INTO v_org_id
  FROM commercial_price_tables cpt
  WHERE cpt.id = p_commercial_price_table_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Commercial price table not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.create', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.create)';
  END IF;

  -- Parent-active guard already enforced by trg_cptv_parent_active.

  IF p_valid_to IS NOT NULL AND p_valid_to <= p_valid_from THEN
    RAISE EXCEPTION 'valid_to must be greater than valid_from';
  END IF;

  -- Alias the table column to avoid ambiguity with the OUT parameter
  -- named `version_number` (PL/pgSQL RETURNS TABLE column name).
  SELECT COALESCE(MAX(cptv.version_number), 0) + 1
  INTO v_version_num
  FROM commercial_price_table_versions cptv
  WHERE cptv.commercial_price_table_id = p_commercial_price_table_id;

  INSERT INTO commercial_price_table_versions (
    organization_id, commercial_price_table_id, version_number,
    valid_from, valid_to, status, version_label, notes,
    created_by
  ) VALUES (
    v_org_id, p_commercial_price_table_id, v_version_num,
    p_valid_from, p_valid_to, 'draft', p_version_label, p_notes,
    v_user_id
  ) RETURNING id INTO v_version_id;

  RETURN QUERY SELECT v_version_id, v_version_num;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_create_commercial_price_table_version(uuid, date, date, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_create_commercial_price_table_version(uuid, date, date, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_create_commercial_price_table_version(uuid, date, date, text, text) TO authenticated;

-- ============================================================
-- D1. fn_add_commercial_price_item_manual — controlled manual insert
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_add_commercial_price_item_manual(
  p_version_id      uuid,
  p_catalog_item_id uuid,
  p_price_amount    numeric
)
RETURNS uuid AS $$
DECLARE
  v_user_id  uuid;
  v_org_id   uuid;
  v_status   text;
  v_item_id  uuid;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_price_amount IS NULL OR p_price_amount < 0 THEN
    RAISE EXCEPTION 'price_amount must be >= 0';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.create', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.create)';
  END IF;

  IF v_status <> 'draft' THEN
    RAISE EXCEPTION 'Cannot add manual item to version with status % (only draft allowed)', v_status;
  END IF;

  INSERT INTO commercial_price_items (
    organization_id, commercial_price_table_version_id, catalog_item_id,
    price_amount, currency, origin_type,
    created_by, updated_by
  ) VALUES (
    v_org_id, p_version_id, p_catalog_item_id,
    p_price_amount, 'BRL', 'manual',
    v_user_id, v_user_id
  ) RETURNING id INTO v_item_id;

  RETURN v_item_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_add_commercial_price_item_manual(uuid, uuid, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_add_commercial_price_item_manual(uuid, uuid, numeric) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_add_commercial_price_item_manual(uuid, uuid, numeric) TO authenticated;

-- ============================================================
-- D2. fn_update_commercial_price_item_price — narrow draft price update
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_update_commercial_price_item_price(
  p_item_id      uuid,
  p_price_amount numeric
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_price_amount IS NULL OR p_price_amount < 0 THEN
    RAISE EXCEPTION 'price_amount must be >= 0';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_items cpi
  JOIN commercial_price_table_versions v ON v.id = cpi.commercial_price_table_version_id
  WHERE cpi.id = p_item_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Item not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.edit', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.edit)';
  END IF;

  IF v_status <> 'draft' THEN
    RAISE EXCEPTION 'Cannot update item in version with status % (only draft allowed)', v_status;
  END IF;

  UPDATE commercial_price_items
  SET price_amount = p_price_amount,
      updated_by   = v_user_id
  WHERE id = p_item_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_update_commercial_price_item_price(uuid, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_update_commercial_price_item_price(uuid, numeric) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_update_commercial_price_item_price(uuid, numeric) TO authenticated;

-- ============================================================
-- D3. fn_delete_commercial_price_item — draft-only delete
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_delete_commercial_price_item(
  p_item_id uuid
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_items cpi
  JOIN commercial_price_table_versions v ON v.id = cpi.commercial_price_table_version_id
  WHERE cpi.id = p_item_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Item not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.edit', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.edit)';
  END IF;

  IF v_status <> 'draft' THEN
    RAISE EXCEPTION 'Cannot delete item from version with status % (only draft allowed)', v_status;
  END IF;

  DELETE FROM commercial_price_items WHERE id = p_item_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_delete_commercial_price_item(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_delete_commercial_price_item(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_delete_commercial_price_item(uuid) TO authenticated;

-- ============================================================
-- E. fn_add_commercial_price_item_from_engine — trusted engine provenance
-- ============================================================
-- The ONLY trusted way to create origin_type = 'pricing_engine'. Calls the
-- authoritative fn_simulate_price(...) and extracts real provenance keys
-- from the simulation result. Direct browser DML fabrication is blocked by
-- the A2 forward guard.

CREATE OR REPLACE FUNCTION public.fn_add_commercial_price_item_from_engine(
  p_version_id                uuid,
  p_catalog_item_id           uuid,
  p_supplier_company_id       uuid,
  p_reference_date            date    DEFAULT current_date,
  p_discount_rate             numeric DEFAULT 0,
  p_commercial_price_amount   numeric DEFAULT NULL
)
RETURNS uuid AS $$
DECLARE
  v_user_id        uuid;
  v_org_id         uuid;
  v_status         text;
  v_sim            jsonb;
  v_sim_status     text;
  v_item_id        uuid;

  v_prov_org          uuid;
  v_prov_supplier     uuid;
  v_prov_cat_item     uuid;
  v_prov_ref_date     date;

  v_prov_cost_table    uuid;
  v_prov_cost_version  uuid;
  v_prov_cost_ver_num  integer;
  v_prov_cost_valid_from date;
  v_prov_cost_valid_to   date;

  v_prov_policy        uuid;
  v_prov_policy_ver    uuid;
  v_prov_policy_ver_num integer;

  v_calculated_price   numeric;
  v_total_cost         numeric;
  v_margin_rate        numeric;
  v_markup_rate        numeric;
  v_effective_price    numeric;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_discount_rate IS NOT NULL AND (p_discount_rate < 0 OR p_discount_rate > 1) THEN
    RAISE EXCEPTION 'discount_rate must be between 0 and 1';
  END IF;

  IF p_commercial_price_amount IS NOT NULL AND p_commercial_price_amount < 0 THEN
    RAISE EXCEPTION 'commercial_price_amount must be >= 0';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.create', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.create)';
  END IF;

  IF NOT has_permission('pricing.calculate', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.calculate)';
  END IF;

  IF v_status <> 'draft' THEN
    RAISE EXCEPTION 'Cannot add engine item to version with status % (only draft allowed)', v_status;
  END IF;

  -- Call authoritative simulation. fn_simulate_price enforces its own auth,
  -- membership and pricing.calculate check — we are double-gating by
  -- permission above for the same effect (defense in depth).
  v_sim := public.fn_simulate_price(
    p_organization_id     => v_org_id,
    p_supplier_company_id => p_supplier_company_id,
    p_catalog_item_id     => p_catalog_item_id,
    p_reference_date      => p_reference_date,
    p_discount_rate       => COALESCE(p_discount_rate, 0)
  );

  v_sim_status := v_sim->>'status';

  IF v_sim_status IS NULL THEN
    RAISE EXCEPTION 'Pricing simulation returned no status';
  END IF;

  -- Accept only business-calculable outcomes
  IF v_sim_status NOT IN ('OK','VIOLATIONS') THEN
    RAISE EXCEPTION 'Pricing simulation not business-calculable: %', v_sim_status;
  END IF;

  -- Extract provenance (use exact keys from fn_simulate_price result)
  v_prov_org       := (v_sim->'provenance'->>'organization_id')::uuid;
  v_prov_supplier  := (v_sim->'provenance'->>'supplier_company_id')::uuid;
  v_prov_cat_item  := (v_sim->'provenance'->>'catalog_item_id')::uuid;
  v_prov_ref_date  := (v_sim->'provenance'->>'reference_date')::date;

  v_prov_cost_table   := (v_sim->'provenance'->'cost'->>'cost_table_id')::uuid;
  v_prov_cost_version := (v_sim->'provenance'->'cost'->>'cost_version_id')::uuid;
  v_prov_cost_ver_num := (v_sim->'provenance'->'cost'->>'cost_version_number')::integer;
  v_prov_cost_valid_from := (v_sim->'provenance'->'cost'->>'cost_valid_from')::date;
  v_prov_cost_valid_to   := (v_sim->'provenance'->'cost'->>'cost_valid_to')::date;

  v_prov_policy       := (v_sim->'provenance'->'policy'->>'pricing_policy_id')::uuid;
  v_prov_policy_ver   := (v_sim->'provenance'->'policy'->>'pricing_policy_version_id')::uuid;
  v_prov_policy_ver_num := (v_sim->'provenance'->'policy'->>'policy_version_number')::integer;

  v_calculated_price := (v_sim->>'calculated_price')::numeric;
  v_total_cost       := (v_sim->>'total_cost')::numeric;
  v_margin_rate      := (v_sim->>'margin_rate')::numeric;
  v_markup_rate      := (v_sim->>'markup_rate')::numeric;
  v_effective_price  := (v_sim->>'effective_price')::numeric;

  IF v_effective_price IS NULL THEN
    RAISE EXCEPTION 'Pricing simulation returned NULL effective_price';
  END IF;

  -- Open the commercial RPC gate so the A2 engine-provenance guard allows
  -- this INSERT. The gate is transaction-scoped, so it does not leak beyond
  -- this function call.
  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  INSERT INTO commercial_price_items (
    organization_id, commercial_price_table_version_id, catalog_item_id,
    price_amount, currency, origin_type,
    source_reference_date,
    source_supplier_company_id,
    source_cost_table_id, source_cost_version_id, source_cost_version_number,
    source_pricing_policy_id, source_pricing_policy_version_id, source_policy_version_number,
    source_calculated_price, source_total_cost,
    source_margin_rate, source_markup_rate, source_effective_price,
    pricing_snapshot,
    created_by, updated_by
  ) VALUES (
    v_org_id, p_version_id, p_catalog_item_id,
    COALESCE(p_commercial_price_amount, v_effective_price), 'BRL', 'pricing_engine',
    v_prov_ref_date,
    v_prov_supplier,
    v_prov_cost_table, v_prov_cost_version, v_prov_cost_ver_num,
    v_prov_policy, v_prov_policy_ver, v_prov_policy_ver_num,
    v_calculated_price, v_total_cost,
    v_margin_rate, v_markup_rate, v_effective_price,
    v_sim,
    v_user_id, v_user_id
  ) RETURNING id INTO v_item_id;

  RETURN v_item_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_add_commercial_price_item_from_engine(uuid, uuid, uuid, date, numeric, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_add_commercial_price_item_from_engine(uuid, uuid, uuid, date, numeric, numeric) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_add_commercial_price_item_from_engine(uuid, uuid, uuid, date, numeric, numeric) TO authenticated;

-- ============================================================
-- F. fn_clone_commercial_price_table_version — atomic clone
-- ============================================================
-- Copies ALL eligible source items atomically. Aborts the whole transaction
-- if any source item references an inactive catalog item (no partial
-- version, no partial item list). Refreshes catalog snapshots from current
-- catalog via the existing 032 snapshot trigger. Preserves lineage to each
-- source item via source_commercial_price_item_id.

CREATE OR REPLACE FUNCTION public.fn_clone_commercial_price_table_version(
  p_source_version_id uuid,
  p_valid_from        date,
  p_valid_to          date DEFAULT NULL,
  p_version_label     text DEFAULT NULL,
  p_notes             text DEFAULT NULL
)
RETURNS TABLE (new_version_id uuid, new_version_number integer) AS $$
DECLARE
  v_user_id        uuid;
  v_org_id         uuid;
  v_table_id       uuid;
  v_version_num    integer;
  v_new_version_id uuid;
  v_source_count   integer;
  v_inactive_count integer;
  v_item           record;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  -- Load source version + parent table
  SELECT v.organization_id, v.commercial_price_table_id
  INTO v_org_id, v_table_id
  FROM commercial_price_table_versions v
  WHERE v.id = p_source_version_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Source version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.create', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.create)';
  END IF;

  IF p_valid_to IS NOT NULL AND p_valid_to <= p_valid_from THEN
    RAISE EXCEPTION 'valid_to must be greater than valid_from';
  END IF;

  -- Lock the parent stable table to serialize version_number allocation
  -- and to prevent the parent from being inactivated mid-clone.
  PERFORM 1 FROM commercial_price_tables
  WHERE id = v_table_id
  FOR UPDATE;

  -- Parent-active guard already enforced on version INSERT below, but we
  -- also check here for a clearer error before allocating.

  -- Verify at least one source item exists
  SELECT count(*) INTO v_source_count
  FROM commercial_price_items
  WHERE commercial_price_table_version_id = p_source_version_id;

  IF v_source_count = 0 THEN
    RAISE EXCEPTION 'Cannot clone a version with no items';
  END IF;

  -- Pre-flight: ALL source items must reference an ACTIVE catalog item
  -- (PRC-05A section 40 invariant).
  SELECT count(*) INTO v_inactive_count
  FROM commercial_price_items cpi
  JOIN catalog_items ci ON ci.id = cpi.catalog_item_id
  WHERE cpi.commercial_price_table_version_id = p_source_version_id
    AND ci.status <> 'active';

  IF v_inactive_count > 0 THEN
    RAISE EXCEPTION 'SOURCE_CONTAINS_INACTIVE_CATALOG_ITEM (% inactive catalog item(s) referenced by source items)', v_inactive_count;
  END IF;

  -- Allocate the next version_number under FOR UPDATE on the parent table.
  SELECT COALESCE(MAX(cptv.version_number), 0) + 1
  INTO v_version_num
  FROM commercial_price_table_versions cptv
  WHERE cptv.commercial_price_table_id = v_table_id;

  -- Open the commercial RPC gate for the duration of this transaction
  -- so the A2 engine-provenance guard allows engine-origin items to be
  -- copied with their original provenance/snapshot.
  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  -- Create the new draft version. The trg_cptv_parent_active trigger will
  -- verify the parent table is active; the trg_cptv_table_same_org trigger
  -- verifies org consistency.
  INSERT INTO commercial_price_table_versions (
    organization_id, commercial_price_table_id, version_number,
    valid_from, valid_to, status, version_label, notes,
    created_by
  ) VALUES (
    v_org_id, v_table_id, v_version_num,
    p_valid_from, p_valid_to, 'draft', p_version_label, p_notes,
    v_user_id
  ) RETURNING id INTO v_new_version_id;

  -- Copy ALL eligible source items atomically. The existing
  -- fn_cpi_snapshot_derive trigger refreshes catalog snapshots. The A2
  -- guard allows engine-origin items because the gate is set.
  --
  -- Lineage (DEC-049): the cloned item's source_commercial_price_item_id
  -- is ALWAYS set to the source item's id, regardless of what the source
  -- item's own lineage was. Cloning produces a fresh lineage edge that
  -- points to the immediate predecessor (the source item being cloned).
  FOR v_item IN
    SELECT id AS source_item_id,
           catalog_item_id, price_amount, currency, origin_type,
           source_reference_date, source_supplier_company_id,
           source_cost_table_id, source_cost_version_id, source_cost_version_number,
           source_pricing_policy_id, source_pricing_policy_version_id, source_policy_version_number,
           source_calculated_price, source_total_cost,
           source_margin_rate, source_markup_rate, source_effective_price,
           pricing_snapshot
    FROM commercial_price_items
    WHERE commercial_price_table_version_id = p_source_version_id
    ORDER BY id
  LOOP
    INSERT INTO commercial_price_items (
      organization_id, commercial_price_table_version_id, catalog_item_id,
      price_amount, currency, origin_type,
      source_commercial_price_item_id,
      source_reference_date, source_supplier_company_id,
      source_cost_table_id, source_cost_version_id, source_cost_version_number,
      source_pricing_policy_id, source_pricing_policy_version_id, source_policy_version_number,
      source_calculated_price, source_total_cost,
      source_margin_rate, source_markup_rate, source_effective_price,
      pricing_snapshot,
      created_by, updated_by
    ) VALUES (
      v_org_id, v_new_version_id, v_item.catalog_item_id,
      v_item.price_amount, v_item.currency, v_item.origin_type,
      -- Lineage: always point to the immediate predecessor (source item).
      v_item.source_item_id,
      v_item.source_reference_date, v_item.source_supplier_company_id,
      v_item.source_cost_table_id, v_item.source_cost_version_id, v_item.source_cost_version_number,
      v_item.source_pricing_policy_id, v_item.source_pricing_policy_version_id, v_item.source_policy_version_number,
      v_item.source_calculated_price, v_item.source_total_cost,
      v_item.source_margin_rate, v_item.source_markup_rate, v_item.source_effective_price,
      v_item.pricing_snapshot,
      v_user_id, v_user_id
    );
  END LOOP;

  -- DO NOT copy commercial_price_exceptions: approvals are version-specific.

  RETURN QUERY SELECT v_new_version_id, v_version_num;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_clone_commercial_price_table_version(uuid, date, date, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_clone_commercial_price_table_version(uuid, date, date, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_clone_commercial_price_table_version(uuid, date, date, text, text) TO authenticated;

-- ============================================================
-- G. fn_bulk_adjust_commercial_prices — server-side bulk adjustments
-- ============================================================
-- Atomic percentage / fixed / rounding operations on draft items only.
-- Uses PostgreSQL numeric for authoritative arithmetic. Resulting price
-- is persisted as the new explicit price_amount; no live formula is stored.

CREATE OR REPLACE FUNCTION public.fn_bulk_adjust_commercial_prices(
  p_version_id        uuid,
  p_operation         text,    -- 'percentage' | 'fixed' | 'round'
  p_rate              numeric DEFAULT NULL,   -- percentage as fraction (e.g. 0.05)
  p_fixed_amount      numeric DEFAULT NULL,   -- signed amount to add
  p_rounding_mode     text    DEFAULT NULL,   -- 'nearest' | 'up' | 'down'
  p_rounding_step     numeric DEFAULT NULL,   -- positive step
  p_item_ids          uuid[]  DEFAULT NULL    -- NULL = all items in version
)
RETURNS integer AS $$
DECLARE
  v_user_id      uuid;
  v_org_id       uuid;
  v_status       text;
  v_updated      integer := 0;
  v_rec          record;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_operation NOT IN ('percentage','fixed','round') THEN
    RAISE EXCEPTION 'Invalid operation % (allowed: percentage, fixed, round)', p_operation;
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.edit', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.edit)';
  END IF;

  IF v_status <> 'draft' THEN
    RAISE EXCEPTION 'Bulk operations only allowed on draft versions (status=%)', v_status;
  END IF;

  -- Pre-flight parameter validation (per-operation requirements). Catching
  -- these here avoids invalid SQL inside the CASE expressions of the per-row
  -- UPDATE below (RAISE is a PL/pgSQL statement, not an expression).
  IF p_operation = 'percentage' AND p_rate IS NULL THEN
    RAISE EXCEPTION 'percentage requires rate';
  END IF;
  IF p_operation = 'fixed' AND p_fixed_amount IS NULL THEN
    RAISE EXCEPTION 'fixed requires fixed_amount';
  END IF;
  IF p_operation = 'round' AND (
       p_rounding_mode IS NULL OR p_rounding_step IS NULL OR p_rounding_step <= 0
     ) THEN
    RAISE EXCEPTION 'round requires mode and positive step';
  END IF;
  IF p_operation = 'round' AND p_rounding_mode NOT IN ('nearest','up','down') THEN
    RAISE EXCEPTION 'Invalid rounding mode %', p_rounding_mode;
  END IF;

  -- Open the commercial RPC gate so the A2 guard allows updates to
  -- engine-origin items (their origin_type remains unchanged; the guard
  -- still fires because UPDATE is allowed to keep engine provenance).
  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  -- Iterate item-by-item so each UPDATE is atomic and individually validated
  -- against the negative-price constraint. The fn_cpi_parent_draft trigger
  -- and the existing fn_cpi_actor trigger ensure actor derivation.
  FOR v_rec IN
    SELECT id, price_amount
    FROM commercial_price_items
    WHERE commercial_price_table_version_id = p_version_id
      AND (p_item_ids IS NULL OR id = ANY(p_item_ids))
  LOOP
    UPDATE commercial_price_items
    SET price_amount = CASE p_operation
          WHEN 'percentage' THEN v_rec.price_amount * (1 + p_rate)
          WHEN 'fixed'      THEN v_rec.price_amount + p_fixed_amount
          WHEN 'round'      THEN
            CASE p_rounding_mode
              WHEN 'nearest' THEN round(v_rec.price_amount / p_rounding_step) * p_rounding_step
              WHEN 'up'     THEN ceil(v_rec.price_amount / p_rounding_step)  * p_rounding_step
              WHEN 'down'   THEN floor(v_rec.price_amount / p_rounding_step) * p_rounding_step
            END
        END,
        updated_by   = v_user_id
    WHERE id = v_rec.id;

    v_updated := v_updated + 1;
  END LOOP;

  -- Final atomic validation: ensure all updated items are still >= 0.
  -- The CHECK constraint at the column level blocks negative values per
  -- UPDATE, but we double-check for clarity.
  IF EXISTS (
    SELECT 1 FROM commercial_price_items
    WHERE commercial_price_table_version_id = p_version_id
      AND (p_item_ids IS NULL OR id = ANY(p_item_ids))
      AND price_amount < 0
  ) THEN
    RAISE EXCEPTION 'Bulk adjustment produced a negative price_amount';
  END IF;

  RETURN v_updated;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_bulk_adjust_commercial_prices(uuid, text, numeric, numeric, text, numeric, uuid[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_bulk_adjust_commercial_prices(uuid, text, numeric, numeric, text, numeric, uuid[]) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_bulk_adjust_commercial_prices(uuid, text, numeric, numeric, text, numeric, uuid[]) TO authenticated;

-- ============================================================
-- H1. fn_request_commercial_price_exception
-- ============================================================
-- Parent lifecycle invariant enforced by the A3 forward guard. Allowed
-- parent states: draft, under_review, approved.

CREATE OR REPLACE FUNCTION public.fn_request_commercial_price_exception(
  p_commercial_price_item_id uuid,
  p_violation_code           text,
  p_reason                   text
)
RETURNS uuid AS $$
DECLARE
  v_user_id  uuid;
  v_org_id   uuid;
  v_version_id uuid;
  v_exception_id uuid;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_violation_code IS NULL OR p_violation_code NOT IN ('BELOW_COST','BELOW_MINIMUM_MARGIN','COMMERCIAL_DEVIATION') THEN
    RAISE EXCEPTION 'Invalid violation_code %', p_violation_code;
  END IF;

  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION 'reason cannot be empty';
  END IF;

  SELECT cpi.organization_id, cpi.commercial_price_table_version_id
  INTO v_org_id, v_version_id
  FROM commercial_price_items cpi
  WHERE cpi.id = p_commercial_price_item_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Commercial price item not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.review', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.review)';
  END IF;

  INSERT INTO commercial_price_exceptions (
    organization_id, commercial_price_table_version_id, commercial_price_item_id,
    violation_code, reason,
    requested_by
  ) VALUES (
    v_org_id, v_version_id, p_commercial_price_item_id,
    p_violation_code, p_reason,
    v_user_id
  ) RETURNING id INTO v_exception_id;

  RETURN v_exception_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_request_commercial_price_exception(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_request_commercial_price_exception(uuid, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_request_commercial_price_exception(uuid, text, text) TO authenticated;

-- ============================================================
-- H2. fn_decide_commercial_price_exception
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_decide_commercial_price_exception(
  p_exception_id   uuid,
  p_decision       text,   -- 'approved' | 'denied'
  p_decision_notes text    DEFAULT NULL
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_decision IS NULL OR p_decision NOT IN ('approved','denied') THEN
    RAISE EXCEPTION 'Invalid decision % (allowed: approved, denied)', p_decision;
  END IF;

  SELECT cpe.organization_id INTO v_org_id
  FROM commercial_price_exceptions cpe
  WHERE cpe.id = p_exception_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Exception not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.exception_approve', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.exception_approve)';
  END IF;

  -- Open the commercial RPC gate so the existing 032
  -- fn_cpe_status_transition trigger permits the status UPDATE.
  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  -- decision_notes is intentionally not persisted (no schema column) but
  -- accepted for forward compatibility; if a column is added later the
  -- RPC signature remains stable.
  UPDATE commercial_price_exceptions
  SET status = p_decision
  WHERE id = p_exception_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_decide_commercial_price_exception(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_decide_commercial_price_exception(uuid, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_decide_commercial_price_exception(uuid, text, text) TO authenticated;

-- ============================================================
-- I1. fn_submit_commercial_price_version — draft → under_review
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_submit_commercial_price_version(
  p_version_id uuid
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
  v_item_count integer;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.review', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.review)';
  END IF;

  IF v_status <> 'draft' THEN
    RAISE EXCEPTION 'Only draft versions can be submitted for review (current status=%)', v_status;
  END IF;

  SELECT count(*) INTO v_item_count
  FROM commercial_price_items
  WHERE commercial_price_table_version_id = p_version_id;

  IF v_item_count = 0 THEN
    RAISE EXCEPTION 'Version must have at least one item before submission';
  END IF;

  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  UPDATE commercial_price_table_versions
  SET status = 'under_review'
  WHERE id = p_version_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_submit_commercial_price_version(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_submit_commercial_price_version(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_submit_commercial_price_version(uuid) TO authenticated;

-- ============================================================
-- I2. fn_return_commercial_price_version_to_draft — under_review → draft
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_return_commercial_price_version_to_draft(
  p_version_id uuid
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.edit', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.edit)';
  END IF;

  IF v_status <> 'under_review' THEN
    RAISE EXCEPTION 'Only under_review versions can be returned to draft (current status=%)', v_status;
  END IF;

  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  UPDATE commercial_price_table_versions
  SET status = 'draft'
  WHERE id = p_version_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_return_commercial_price_version_to_draft(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_return_commercial_price_version_to_draft(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_return_commercial_price_version_to_draft(uuid) TO authenticated;

-- ============================================================
-- I3. fn_approve_commercial_price_version — under_review → approved
-- ============================================================
-- Approval may occur while commercial exception requests are pending —
-- this enables separation of duties. The publish RPC remains the final
-- blocking gate for outstanding exceptions.

CREATE OR REPLACE FUNCTION public.fn_approve_commercial_price_version(
  p_version_id uuid
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.approve', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.approve)';
  END IF;

  IF v_status <> 'under_review' THEN
    RAISE EXCEPTION 'Only under_review versions can be approved (current status=%)', v_status;
  END IF;

  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  -- approved_by/at are derived by the existing 032
  -- fn_cptv_validate_status_transition trigger; we only set status here.
  UPDATE commercial_price_table_versions
  SET status = 'approved'
  WHERE id = p_version_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_approve_commercial_price_version(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_approve_commercial_price_version(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_approve_commercial_price_version(uuid) TO authenticated;

-- ============================================================
-- I4. fn_cancel_commercial_price_version
-- ============================================================
-- Allowed: draft, under_review, approved → cancelled.
-- Not allowed via RPC: scheduled, active, superseded (already terminal).

CREATE OR REPLACE FUNCTION public.fn_cancel_commercial_price_version(
  p_version_id uuid
)
RETURNS void AS $$
DECLARE
  v_user_id uuid;
  v_org_id  uuid;
  v_status  text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id
  FOR UPDATE;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.approve', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.approve)';
  END IF;

  IF v_status NOT IN ('draft','under_review','approved') THEN
    RAISE EXCEPTION 'Cannot cancel version with status % (allowed: draft, under_review, approved)', v_status;
  END IF;

  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  UPDATE commercial_price_table_versions
  SET status = 'cancelled'
  WHERE id = p_version_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_cancel_commercial_price_version(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_cancel_commercial_price_version(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_cancel_commercial_price_version(uuid) TO authenticated;

-- ============================================================
-- J. fn_validate_commercial_price_version — publish readiness validator
-- ============================================================
-- Read-only JSONB result. Does NOT mutate data. Authoritative gate for
-- fn_publish_commercial_price_version. Does NOT reimplement pricing
-- formulas — it inspects trusted snapshots and explicit stored values
-- only (DEC-040 + section 40 invariant).

CREATE OR REPLACE FUNCTION public.fn_validate_commercial_price_version(
  p_version_id uuid
)
RETURNS jsonb AS $$
DECLARE
  v_user_id    uuid;
  v_org_id     uuid;
  v_status     text;
  v_item_count integer;
  v_pending_exc integer;
  v_denied_exc  integer;
  v_required_exc_codes text[] := ARRAY[]::text[];
  v_missing_codes text[] := ARRAY[]::text[];
  v_violations_count integer := 0;
  v_blockers text[] := ARRAY[]::text[];
  v_item record;
  v_snap_violations text[];
  v_needed_codes text[];
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status
  INTO v_org_id, v_status
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.view', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.view)';
  END IF;

  -- Item count
  SELECT count(*) INTO v_item_count
  FROM commercial_price_items
  WHERE commercial_price_table_version_id = p_version_id;

  -- Pending + denied exceptions
  SELECT count(*) INTO v_pending_exc
  FROM commercial_price_exceptions
  WHERE commercial_price_table_version_id = p_version_id
    AND status = 'requested';

  SELECT count(*) INTO v_denied_exc
  FROM commercial_price_exceptions
  WHERE commercial_price_table_version_id = p_version_id
    AND status = 'denied';

  -- Compute required exception codes from trusted engine provenance only
  FOR v_item IN
    SELECT id, price_amount, origin_type,
           source_total_cost, source_effective_price, pricing_snapshot
    FROM commercial_price_items
    WHERE commercial_price_table_version_id = p_version_id
  LOOP
    IF v_item.origin_type <> 'pricing_engine' THEN
      CONTINUE;
    END IF;

    v_needed_codes := ARRAY[]::text[];

    -- BELOW_COST: explicit stored comparison (NOT a recomputation)
    IF v_item.source_total_cost IS NOT NULL
       AND v_item.price_amount < v_item.source_total_cost THEN
      v_needed_codes := array_append(v_needed_codes, 'BELOW_COST');
    END IF;

    -- COMMERCIAL_DEVIATION: price below source_effective_price
    IF v_item.source_effective_price IS NOT NULL
       AND v_item.price_amount < v_item.source_effective_price THEN
      v_needed_codes := array_append(v_needed_codes, 'COMMERCIAL_DEVIATION');
    END IF;

    -- BELOW_MINIMUM_MARGIN: from trusted pricing_snapshot only
    IF v_item.pricing_snapshot IS NOT NULL AND jsonb_typeof(v_item.pricing_snapshot) = 'array' THEN
      SELECT COALESCE(array_agg(value #>> '{}'), ARRAY[]::text[])
      INTO v_snap_violations
      FROM jsonb_array_elements(v_item.pricing_snapshot) AS value
      WHERE value #>> '{}' = 'BELOW_MINIMUM_MARGIN';

      IF array_length(v_snap_violations, 1) > 0 THEN
        v_needed_codes := array_append(v_needed_codes, 'BELOW_MINIMUM_MARGIN');
      END IF;
    ELSIF v_item.pricing_snapshot IS NOT NULL
          AND v_item.pricing_snapshot ? 'violations'
          AND jsonb_typeof(v_item.pricing_snapshot->'violations') = 'array' THEN
      IF v_item.pricing_snapshot->'violations' ? 'BELOW_MINIMUM_MARGIN' THEN
        v_needed_codes := array_append(v_needed_codes, 'BELOW_MINIMUM_MARGIN');
      END IF;
    END IF;

    -- For each needed code, ensure an APPROVED exception exists
    IF array_length(v_needed_codes, 1) > 0 THEN
      SELECT array_agg(c) INTO v_required_exc_codes
      FROM unnest(v_needed_codes) AS c
      WHERE NOT EXISTS (
        SELECT 1 FROM commercial_price_exceptions cpe
        WHERE cpe.commercial_price_item_id = v_item.id
          AND cpe.violation_code = c
          AND cpe.status = 'approved'
      );

      IF v_required_exc_codes IS NOT NULL AND array_length(v_required_exc_codes, 1) > 0 THEN
        v_missing_codes := array_cat(v_missing_codes, v_required_exc_codes);
      END IF;

      v_violations_count := v_violations_count + array_length(v_needed_codes, 1);
    END IF;
  END LOOP;

  -- Compose blockers
  IF v_status <> 'approved' THEN
    v_blockers := array_append(v_blockers, 'VERSION_NOT_APPROVED:' || v_status);
  END IF;
  IF v_item_count = 0 THEN
    v_blockers := array_append(v_blockers, 'VERSION_EMPTY');
  END IF;
  IF v_pending_exc > 0 THEN
    v_blockers := array_append(v_blockers, 'PENDING_EXCEPTIONS');
  END IF;
  IF v_denied_exc > 0 THEN
    v_blockers := array_append(v_blockers, 'DENIED_EXCEPTIONS');
  END IF;
  IF array_length(v_missing_codes, 1) > 0 THEN
    v_blockers := array_append(v_blockers, 'MISSING_APPROVED_EXCEPTIONS');
  END IF;

  RETURN jsonb_build_object(
    'version_id', p_version_id,
    'organization_id', v_org_id,
    'status', v_status,
    'ready', array_length(v_blockers, 1) IS NULL,
    'blockers', to_jsonb(v_blockers),
    'warnings', to_jsonb(ARRAY[]::text[]),
    'item_count', v_item_count,
    'pending_exception_count', v_pending_exc,
    'denied_exception_count', v_denied_exc,
    'required_exception_count', v_violations_count,
    'missing_exception_codes', to_jsonb(COALESCE(v_missing_codes, ARRAY[]::text[]))
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_validate_commercial_price_version(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_validate_commercial_price_version(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_validate_commercial_price_version(uuid) TO authenticated;

-- ============================================================
-- K. fn_publish_commercial_price_version — approved → active/scheduled
-- ============================================================
-- Mirrors the cost module temporal semantics (DEC-028/029):
--   - valid_from <= current_date  → new version becomes active; all
--     other active/scheduled versions for this table are superseded
--     (EXCLUDE constraint satisfied because they leave the WHERE clause).
--   - valid_from >  current_date  → new version becomes scheduled; the
--     current active predecessor stays active with valid_to closed to
--     the new valid_from; only OVERLAPPING scheduled versions are
--     superseded (EXCLUDE satisfied by adjacency).

CREATE OR REPLACE FUNCTION public.fn_publish_commercial_price_version(
  p_version_id uuid
)
RETURNS void AS $$
DECLARE
  v_user_id    uuid;
  v_org_id     uuid;
  v_status     text;
  v_valid_from date;
  v_valid_to   date;
  v_table_id   uuid;
  v_table_status text;
  v_new_status text;
  v_ready      jsonb;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT v.organization_id, v.status, v.valid_from, v.valid_to, v.commercial_price_table_id
  INTO v_org_id, v_status, v_valid_from, v_valid_to, v_table_id
  FROM commercial_price_table_versions v
  WHERE v.id = p_version_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Version not found';
  END IF;

  IF NOT is_member_of(v_org_id) THEN
    RAISE EXCEPTION 'Not a member of this organization';
  END IF;

  IF NOT has_permission('pricing.commercial.publish', v_org_id) THEN
    RAISE EXCEPTION 'Insufficient permissions (requires pricing.commercial.publish)';
  END IF;

  IF v_status <> 'approved' THEN
    RAISE EXCEPTION 'Only approved versions can be published (current status=%)', v_status;
  END IF;

  SELECT status INTO v_table_status
  FROM commercial_price_tables
  WHERE id = v_table_id;

  IF v_table_status IS NULL THEN
    RAISE EXCEPTION 'Commercial price table not found';
  END IF;

  IF v_table_status <> 'active' THEN
    RAISE EXCEPTION 'Cannot publish: commercial price table is inactive';
  END IF;

  -- Run the publish readiness validator — it is the authoritative gate.
  v_ready := public.fn_validate_commercial_price_version(p_version_id);

  IF NOT (v_ready->>'ready')::boolean THEN
    RAISE EXCEPTION 'Publish validation failed: %', v_ready->'blockers';
  END IF;

  -- Date-driven status
  IF v_valid_from > current_date THEN
    v_new_status := 'scheduled';
  ELSE
    v_new_status := 'active';
  END IF;

  -- Open the commercial RPC gate for the duration of this transaction.
  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  IF v_new_status = 'active' THEN
    -- Active publish: supersede ALL other active/scheduled versions for
    -- this table. They leave the EXCLUDE WHERE clause; the new version
    -- is the only active/scheduled row remaining.
    UPDATE commercial_price_table_versions
    SET status = 'superseded',
        superseded_at = now(),
        valid_to = CASE
          WHEN v_valid_from > valid_from THEN v_valid_from
          ELSE valid_to
        END
    WHERE commercial_price_table_id = v_table_id
      AND id != p_version_id
      AND status IN ('active', 'scheduled');
  ELSE
    -- Scheduled publish: keep predecessor ACTIVE, close its valid_to.
    UPDATE commercial_price_table_versions
    SET valid_to = v_valid_from
    WHERE commercial_price_table_id = v_table_id
      AND id != p_version_id
      AND status = 'active'
      AND valid_from < v_valid_from
      AND (valid_to IS NULL OR valid_to > v_valid_from);

    -- Supersede OVERLAPPING scheduled versions (daterange '[)' semantics).
    UPDATE commercial_price_table_versions
    SET status = 'superseded',
        superseded_at = now()
    WHERE commercial_price_table_id = v_table_id
      AND id != p_version_id
      AND status = 'scheduled'
      AND daterange(valid_from, valid_to, '[)') && daterange(v_valid_from, v_valid_to, '[)');
  END IF;

  -- Publish the new version. approved_by/at/published_by/at are derived
  -- by the existing 032 fn_cptv_validate_status_transition trigger.
  UPDATE commercial_price_table_versions
  SET status = v_new_status
  WHERE id = p_version_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_publish_commercial_price_version(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_publish_commercial_price_version(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_publish_commercial_price_version(uuid) TO authenticated;

-- ============================================================
-- L. fn_sync_commercial_price_version_status — idempotent cutover
-- ============================================================
-- Activates scheduled versions whose valid_from <= reference_date and
-- supersedes the active predecessor. Safe to run repeatedly.

CREATE OR REPLACE FUNCTION public.fn_sync_commercial_price_version_status(
  p_reference_date date DEFAULT current_date
)
RETURNS integer AS $$
DECLARE
  v_user_id uuid;
  v_count   integer := 0;
  v_sched   record;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_reference_date IS NULL THEN
    RAISE EXCEPTION 'Reference date is required';
  END IF;

  PERFORM set_config('app.commercial_price_rpc_active', 'true', true);

  FOR v_sched IN
    SELECT s.id, s.commercial_price_table_id, s.valid_from, s.valid_to, s.organization_id
    FROM commercial_price_table_versions s
    WHERE s.status = 'scheduled'
      AND s.valid_from <= p_reference_date
      AND (s.valid_to IS NULL OR s.valid_to > p_reference_date)
    ORDER BY s.commercial_price_table_id, s.valid_from ASC, s.version_number ASC
  LOOP
    IF NOT has_permission('pricing.commercial.publish', v_sched.organization_id) THEN
      RAISE EXCEPTION 'Insufficient permissions for commercial version activation';
    END IF;

    -- Supersede the active predecessor whose range ends where this begins.
    UPDATE commercial_price_table_versions
    SET status = 'superseded',
        superseded_at = now()
    WHERE commercial_price_table_id = v_sched.commercial_price_table_id
      AND status = 'active'
      AND id NOT IN (
        SELECT s2.id
        FROM commercial_price_table_versions s2
        WHERE s2.commercial_price_table_id = v_sched.commercial_price_table_id
          AND s2.status = 'scheduled'
          AND s2.valid_from <= p_reference_date
          AND (s2.valid_to IS NULL OR s2.valid_to > p_reference_date)
      )
      AND valid_from <= v_sched.valid_from
      AND (valid_to IS NULL OR valid_to >= v_sched.valid_from);

    -- Activate the scheduled version. published_by/at are derived by the
    -- existing 032 fn_cptv_validate_status_transition trigger.
    UPDATE commercial_price_table_versions
    SET status = 'active'
    WHERE id = v_sched.id;

    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.fn_sync_commercial_price_version_status(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_sync_commercial_price_version_status(date) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_sync_commercial_price_version_status(date) TO authenticated;

-- ============================================================
-- M. INTERNAL HELPER REVOKES
-- ============================================================
-- Integrity triggers and forward guards are internal — never exposed to
-- anonymous clients. EXECUTE stays with `authenticated` for the same
-- reason documented in 032 (triggers run with the privileges of the
-- performing role — revoking breaks trigger invocation).

DO $$
DECLARE
  v_rec record;
BEGIN
  FOR v_rec IN
    SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS args
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname IN (
        'fn_cptv_parent_active',
        'fn_cpi_engine_provenance_guard',
        'fn_cpe_parent_editable'
      )
  LOOP
    EXECUTE format(
      'REVOKE EXECUTE ON FUNCTION public.%I(%s) FROM PUBLIC, anon',
      v_rec.proname, v_rec.args
    );
  END LOOP;
END $$;
